### PR TITLE
store_ location

### PR DESCRIPTION
**Pull request by LayZ2001**
not complete just pushed the change so i can access the rest of the main file

### CODE REVIEW

**Review by JackHDean21 — CHANGES_REQUESTED** [review]
be better

**Review by j-forcer90 — CHANGES_REQUESTED** [review]
not much point in merging if it doesn't work

**Review by Zeeks17 — CHANGES_REQUESTED** [review]
FIX IT!

**Comment by LayZ2001** [comment]
be nice guys :(

**Pull request closed without merging**
